# Generated by Django 4.1.3 on 2022-12-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_rename_mombre_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticia/defualt.jpg', null=True, upload_to='noticia'),
        ),
    ]
