# Generated by Django 4.1.3 on 2022-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_alter_noticia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticia/default.jpg', null=True, upload_to='noticia'),
        ),
    ]
